### ISSUE TITLE
No such file error

### ISSUE THREAD

**Issue by saurabhnemade** [Jam3/devtool#100]
I just installed this on my Linux Mint

Got following error while running js files:
`fs.js:634
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/devtool/node_modules/electron/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/devtool/node_modules/electron/index.js:4:42)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
`

Any ideas?

**Comment by wb2110** [comment]
it looks like you do not install the electron properly,try reinstall devtool may resolve the problem
