### ISSUE TITLE
Module version mismatch. Expected 50, got 51.

### ISSUE THREAD

**Issue by qwemaze** [Jam3/devtool#102]
NodeJS v7.0.0

When running in node everything is fine.

```
/home/qwemaze/projects/containers/kholodilnikcompose/kholodilnik/node_modules/sharp/index.js
Module version mismatch. Expected 50, got 51.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/qwemaze/projects/containers/kholodilnikcompose/kholodilnik/node_modules/sharp/index.js:12:13)
    at Module._compile (module.js:556:32)
    at Object.devtoolCompileModule [as .js] (/home/qwemaze/.nvm/versions/node/v7.0.0/lib/node_modules/devtool/lib/require-hook.js:32:14)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/qwemaze/projects/containers/kholodilnikcompose/kholodilnik/dbmodel/extender/item/router.js:4:15)
    at Module._compile (module.js:556:32)
    at Object.devtoolCompileModule [as .js] (/home/qwemaze/.nvm/versions/node/v7.0.0/lib/node_modules/devtool/lib/require-hook.js:32:14)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at fs.readdirSync.map (/home/qwemaze/projects/containers/kholodilnikcompose/kholodilnik/requireDir.js:11:49)
    at Array.map (native)
    at module.exports.e (/home/qwemaze/projects/containers/kholodilnikcompose/kholodilnik/requireDir.js:10:31)
```

**Comment by bruceCzK** [comment]
Have you tried `npm rebuild`?

**Comment by avdg** [comment]
In the worst case you have to run npm install dev took again. That at least worked for me with other packages where npm rebuild and npm install failed.

**Comment by talltyler** [comment]
I'm having the same issue. My application runs fine outside of Devtool. When running inside it throws these errors. It is not stuck on anything but the native modules. I assume I should be running the same Node version as Devtools was packaged with but I don't know what version that is. I'm currently on Node version 6.9.1.

**Comment by talltyler** [comment]
This seems to be related to Electron, not Devtool. This should be the fix http://electron.atom.io/docs/tutorial/using-native-node-modules/

**Comment by Figedi** [comment]
The problem is somewhat related to electron, as the newest version to this date (1.4.6) uses the module version 50, while node 7 uses version 51. All we can do is wait until electron releases a newer version with a newer module version. I downgraded devtool and node for this sole reason in order for both to match the module version
