### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by RifeWang** [Jam3/devtool#117]
when i ` npm install devtool -g`  but got error:
```
/usr/local/bin/devtool -> /usr/local/lib/node_modules/devtool/bin/index.js

> fsevents@1.1.1 install /usr/local/lib/node_modules/devtool/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/devtool/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> electron@1.4.15 postinstall /usr/local/lib/node_modules/devtool/node_modules/electron
> node install.js

/usr/local/lib/node_modules/devtool/node_modules/electron/install.js:46
  throw err
  ^

Error: connect ETIMEDOUT 54.231.115.43:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
/usr/local/lib
└── (empty)

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "devtool" "-g"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron@1.4.15 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.4.15 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wangying/npm-debug.log
npm ERR! code 1
```
i think its the electron problem, so i install electron again , but cant install.

**Comment by RifeWang** [comment]
solved
