### ISSUE TITLE
heapdump support

### ISSUE THREAD

**Issue by MadLittleMods** [Jam3/devtool#50]
Using `heapdump` in app: `devtool web.js` throws the following error while `node web.js` doesn't.

 - `heapdump@0.3.7`
 - `devtool@1.8.3`
 - `node@4.2.3`

```
/some-project/node_modules/heapdump/lib/main.js
Cannot find module '../build/Debug/addon'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/some-project/node_modules/heapdump/lib/main.js:18:15)
    at Module._compile (module.js:425:26)
    at Object.devtoolCompileModule [as .js] (/usr/local/lib/node_modules/devtool/lib/require-hook.js:30:14)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/some-project/server/utils/diagnostics.js:42:18)
    at Module._compile (module.js:425:26)
    at Object.devtoolCompileModule [as .js] (/usr/local/lib/node_modules/devtool/lib/require-hook.js:30:14)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/some-project/server/web.js:3:1)
    at Module._compile (module.js:425:26)
    at Object.devtoolCompileModule [as .js] (/usr/local/lib/node_modules/devtool/lib/require-hook.js:30:14)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/some-project/web.js:7:1)
    at Module._compile (module.js:425:26)
    at Object.devtoolCompileModule [as .js] (/usr/local/lib/node_modules/devtool/lib/require-hook.js:30:14)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/devtool/lib/preload.js:76:16)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

**Comment by MadLittleMods** [comment]
This probably needs to be built for the right version of electron. [See gotchas](
If a native module does not work, you may need to rebuild it for the right version of Electron)
