### ISSUE TITLE
Undefined electron `app` in server.js

### ISSUE THREAD

**Issue by MadLittleMods** [Jam3/devtool#54]
Running `devtool` results in the following error in the terminal. Could be related to me starting to use [`nvm`](https://github.com/creationix/nvm)?

 - `node@v5.9.0`
 - `npm@3.7.3` or `npm@2.15.1`
 - `devtool@1.8.3`

```
$ devtool
App threw an error when running [TypeError: Cannot read property 'commandLine' of undefined]
/Users/eric/.nvm/versions/node/v5.9.0/lib/node_modules/devtool/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app/main.js:269
      throw e;
      ^

TypeError: Cannot read property 'commandLine' of undefined
    at Object.<anonymous> (/Users/eric/.nvm/versions/node/v5.9.0/lib/node_modules/devtool/server.js:20:4)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at loadApplicationPackage (/Users/eric/.nvm/versions/node/v5.9.0/lib/node_modules/devtool/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app/main.js:257:23)
    at Object.<anonymous> (/Users/eric/.nvm/versions/node/v5.9.0/lib/node_modules/devtool/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app/main.js:289:5)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
```

Opening a new tab context, actually launches a electron instance and pops the same error in a dialog modal:

![](https://i.imgur.com/AFQBDlB.png)

**Comment by mattdesl** [comment]
Any way I can reproduce this?

**Comment by MadLittleMods** [comment]
I am unable to reproduce it today. But it occurred even after reinstalling etc.

I didn't restart the machine (just sleep).

**Comment by zeronone** [comment]
I can reproduce the error in Node `v4.4.0` but it disappears in other versions (`v6.0.0` and `v4.4.4`).
