### ISSUE TITLE
electron-prebuilt postinstall script not finishing

### ISSUE THREAD

**Issue by aleclarson** [Jam3/devtool#67]
It seems the `postinstall` script of `electron-prebuilt` sometimes fails to complete, resulting in a missing configuration file.

```sh
> devtool

  fs.js:549
    return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                   ^

  Error: ENOENT: no such file or directory, open '/Users/aleclarson/devtool/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (/Users/aleclarson/devtool/node_modules/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

You can get around this using:

```sh
cd $HOME/devtool/node_modules/electron-prebuilt
sudo node install.js
```

Is there something that can be done to automate this?

Or is this issue the responsibility of `electron-prebuilt` contributors?

**Comment by mattdesl** [comment]
Do you have the error logs from when the install failed? Does it happen every time you `npm install devtool -g`? I haven't seen this and I'm not able to reproduce it.

If it persists with the latest version of devtool, try posting a new issue in [electron-prebuilt](https://github.com/electron-userland/electron-prebuilt/issues).
